// Scheduler checks. Usage: npm run test:srs
import { schedule, previewIntervals, formatDelay, streak, dayKey, endOfDay, type Grade } from "../src/lib/srs.ts";
let fail = 0;
const eq = (label: string, a: unknown, b: unknown) => { const ok = JSON.stringify(a) === JSON.stringify(b); if (!ok) fail++; console.log(ok ? "PASS" : "FAIL", label, ok ? "" : `→ got ${JSON.stringify(a)} expected ${JSON.stringify(b)}`); };
const now = new Date("2026-10-01T15:00:00Z");
eq("new item buttons match design", previewIntervals(null), { 1: "< 1 min", 2: "6 min", 3: "1 dia", 4: "4 dias" });
let s = schedule(null, 3, now);
eq("good graduates to review, 1 day", [s.state, s.interval_days], ["review", 1]);
const days = (st: typeof s, from: Date) => Math.round((new Date(st.due_at).getTime() - from.getTime()) / 86400000);
let t = new Date(s.due_at); s = schedule(s, 3, t);
eq("second good: max(1+1, 1*2.5) = 3 days", s.interval_days, 3);
t = new Date(s.due_at); s = schedule(s, 3, t);
eq("third good: 3*2.5 = 8 days", s.interval_days, 8);
eq("due in 8 days", days(s, t), 8);
t = new Date(s.due_at); const lapse = schedule(s, 1, t);
eq("again on review -> relearning, lapses 1, ease 2.3", [lapse.state, lapse.lapses, lapse.ease], ["relearning", 1, 2.3]);
eq("relearning buttons", previewIntervals(lapse), { 1: "< 1 min", 2: "6 min", 3: "4 dias", 4: "5 dias" });
const back = schedule(lapse, 3, t);
eq("relearn good -> review at half interval (4 days)", [back.state, back.interval_days], ["review", 4]);
const hard = schedule(s, 2 as Grade, t);
eq("hard: 8*1.2=9.6 -> 10, ease 2.35", [hard.interval_days, hard.ease], [10, 2.35]);
const easy = schedule(s, 4 as Grade, t);
eq("easy: 8*2.5*1.3=26, ease 2.65", [easy.interval_days, easy.ease], [26, 2.65]);
let e = schedule(null, 1, now); for (let i = 0; i < 20; i++) e = schedule({ ...e, state: "review", interval_days: 5 }, 1, now);
eq("ease never below 1.3", e.ease, 1.3);
eq("formatDelay months", formatDelay(65 * 86400000), "2 meses");
eq("dayKey uses Brasília time", dayKey(new Date("2026-10-02T02:00:00Z")), "2026-10-01");
eq("endOfDay", endOfDay(now), "2026-10-02T02:59:59.999Z");
eq("streak with today pending", streak(new Set(["2026-09-29", "2026-09-30"]), now), { count: 2, todayDone: false });
eq("streak with today done", streak(new Set(["2026-09-30", "2026-10-01"]), now), { count: 2, todayDone: true });
eq("streak broken", streak(new Set(["2026-09-28"]), now), { count: 0, todayDone: false });
process.exit(fail ? 1 : 0);
